version: '3.8'

services:
  # Django Application
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=AI_Legal_Explainer.production_settings
      - DB_HOST=db
      - DB_NAME=ai_legal_explainer
      - DB_USER=root
      - DB_PASSWORD=password123
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - db
      - redis
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./ai_models:/opt/ai_models
    restart: unless-stopped

  # MySQL Database
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ai_legal_explainer
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Redis for caching and Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Celery Worker
  celery:
    build: .
    command: celery -A AI_Legal_Explainer worker --loglevel=info
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=AI_Legal_Explainer.production_settings
      - DB_HOST=db
      - DB_NAME=ai_legal_explainer
      - DB_USER=root
      - DB_PASSWORD=password123
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./ai_models:/opt/ai_models
    restart: unless-stopped

  # Celery Beat (Scheduler)
  celery-beat:
    build: .
    command: celery -A AI_Legal_Explainer beat --loglevel=info
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=AI_Legal_Explainer.production_settings
      - DB_HOST=db
      - DB_NAME=ai_legal_explainer
      - DB_USER=root
      - DB_PASSWORD=password123
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./ai_models:/opt/ai_models
    restart: unless-stopped

  # Nginx (Optional - for production-like setup)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
